FROM openjdk:8-jre

ENV ACTIVEMQ_TCP=61616 ACTIVEMQ_AMQP=5672 ACTIVEMQ_STOMP=61613 ACTIVEMQ_MQTT=1883 ACTIVEMQ_WS=61614 ACTIVEMQ_UI=8161 JMX=1616

ENV ACTIVEMQ_HOME /opt/activemq

COPY apache-activemq-5.15.9 $ACTIVEMQ_HOME  

WORKDIR $ACTIVEMQ_HOME

EXPOSE $ACTIVEMQ_TCP $ACTIVEMQ_AMQP $ACTIVEMQ_STOMP $ACTIVEMQ_MQTT $ACTIVEMQ_WS $ACTIVEMQ_UI $JMX

CMD ["/bin/sh", "-c", "bin/activemq console"]
